name: 四大科技指数每日分析

on:
  schedule:
    # 每天 UTC 07:00 执行 (北京时间 15:00，A股/港股收盘后)
    - cron: '0 7 * * *'

  # 允许手动触发
  workflow_dispatch:

jobs:
  analyze-and-email:
    runs-on: ubuntu-latest

    steps:
    - name: 检出代码
      uses: actions/checkout@v4

    - name: 设置Python环境
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt || echo "No requirements.txt found, installing manually"
        pip install yfinance pandas numpy akshare pyyaml tqdm

    - name: 创建必要目录
      run: |
        mkdir -p config
        mkdir -p logs
        cat > config/email_config.yaml << EOF
        smtp:
          server: smtp.qq.com
          port: 465

        sender:
          email: ${{ secrets.SENDER_EMAIL }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          name: 科技指数分析系统

        recipients:
          - ${{ secrets.RECIPIENT_EMAIL }}

        send_no_alert_email: false
        EOF

    - name: 运行分析并发送邮件
      run: |
        echo "开始执行四大科技指数分析..."
        python scripts/tech_indices_analysis/run_tech_comprehensive_analysis.py --email --save logs/report_$(date +%Y%m%d).txt
        echo "分析完成！"
      env:
        PYTHONPATH: ${{ github.workspace }}

    - name: 上传分析报告和日志
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: analysis-report-${{ github.run_number }}
        path: |
          logs/*.log
          logs/*.txt
        retention-days: 7
        if-no-files-found: warn
