name: 均线偏离度监控

on:
  schedule:
    # 每个交易日 15:10 (UTC+8) 执行，即北京时间 15:10
    # GitHub Actions 使用 UTC 时间，需要减8小时，所以是 07:10 UTC
    - cron: '10 7 * * 1-5'  # 周一到周五 UTC 07:10 = 北京时间 15:10

  # 允许手动触发
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
    - name: 检出代码
      uses: actions/checkout@v3

    - name: 设置 Python 环境
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: 安装系统依赖
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential wget

    - name: 安装 TA-Lib C 库
      run: |
        cd /tmp
        wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
        tar -xzf ta-lib-0.4.0-src.tar.gz
        cd ta-lib/
        ./configure --prefix=/usr
        make
        sudo make install

    - name: 安装 Python 依赖
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: 创建邮箱配置文件
      run: |
        cat > email_config.yaml << EOF
        smtp:
          server: ${{ secrets.SMTP_SERVER }}
          port: ${{ secrets.SMTP_PORT }}

        sender:
          email: ${{ secrets.SENDER_EMAIL }}
          password: ${{ secrets.SENDER_PASSWORD }}
          name: ${{ secrets.SENDER_NAME }}

        recipients:
          - ${{ secrets.RECIPIENT_EMAIL }}

        send_no_alert_email: false
        EOF

    - name: 运行监控并发送邮件
      run: |
        python scripts/position_analysis/run_ma_deviation_monitor.py --email --quiet --retry 5
      env:
        TZ: Asia/Shanghai  # 设置时区为北京时间

    - name: 上传日志（如果失败）
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: monitor-logs
        path: logs/
        retention-days: 7
